---
baseURL: 'https://varjoinen.github.io'
languageCode: 'en-us'
title: 'Varjoinen'
theme: 'massively'

params:
  settings:
    googleanalytics: 'UA-35434469-3'
  posts:
    foldername: 'posts'
    pagesize: '6'
    featuredpost: 'true'

languages:
  en:
    languageName: 'English'
